language: node_js
sudo: required
before_script:
  - npm install -g bower polymer-cli@next
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
script:
  - npm install
  - bower install
  - xvfb-run polymer test
dist: trusty
